-- Creating the TBL_OB_ACCOUNT table
CREATE TABLE `global-tech-ai.global_banking_protected.TBL_OB_ACCOUNT` (
  BANK_CODE STRING NOT NULL,
  REAL_ACNO STRING NOT NULL,
  REAL_CUST_ID NUMERIC NOT NULL,
  BALANCE NUMERIC,
  CURRENCY STRING,
  UPDATE_DTTM TIMESTAMP
);

-- Creating the TBL_CUSTOMER_CONSENT table
CREATE TABLE `global-tech-ai.global_banking_protected.TBL_CUSTOMER_CONSENT` (
  REAL_CUST_ID NUMERIC NOT NULL,
  BANK_CODE STRING NOT NULL,
  CONSENT BOOLEAN,
  EVENT_TIME TIMESTAMP
);

-- Creating the TBL_FX_RATE table
CREATE TABLE `global-tech-ai.external_data.TBL_FX_RATE` (
  FROM_CURRENCY STRING NOT NULL,
  TO_CURRENCY STRING NOT NULL,
  EXCHANGE_RATE FLOAT64,
  ACCURACY INT64,
  TIMESTAMP TIMESTAMP
);

-- Creating the TBL_FACT_CUSTOMER_BANK table with partitioning
CREATE TABLE `global-tech-ai.global_banking.TBL_FACT_CUSTOMER_BANK` (
  HASHED_REAL_CUST_ID STRING NOT NULL,
  HASHED_REAL_ACNO STRING NOT NULL,
  BANK_CODE STRING NOT NULL,
  AVG_BALANCE_HKD NUMERIC,
  FIRST_CONSENT_DATE TIMESTAMP,
  EXIT_CONSENT_DATE TIMESTAMP,
  TOP_AVG_BANK STRING,
  UPDATE_DTTM TIMESTAMP
)
PARTITION BY DATE(UPDATE_DTTM);

-- Creating the TBL_HIST_BANK_TOP_COMPETITOR table with partitioning
CREATE TABLE `global-tech-ai.global_banking.TBL_HIST_BANK_TOP_COMPETITOR` (
  HASHED_REAL_CUST_ID STRING NOT NULL,
  BANK_CODE_TOP_COMPETITOR STRING NOT NULL,
  EVENT_DATE TIMESTAMP NOT NULL
)
PARTITION BY DATE(EVENT_DATE);

CREATE TABLE `global-tech-ai.global_banking.TBL_DATA_READINESS` (
  TABLE_NAME STRING NOT NULL,
  DATA_LOAD_DATE TIMESTAMP NOT NULL,
  RECORD_COUNT INT64,
  STATUS STRING NOT NULL
) OPTIONS(
  description="Readiness table for signaling data users about the availability and status of data tables"
);
